# Changes here will be overwritten by Copier
_commit: v5.3.4
_src_path: gh:eccenca/cmem-plugin-template
author_mail: robert.klose@eccenca.com
author_name: TODO
github_page: ''
project_description: TODO
project_slug: irdi
pypi: false

