# Changes here will be overwritten by Copier
_commit: v7.0.0
_src_path: gh:eccenca/cmem-plugin-template
author_mail: cmempy-developer@eccenca.com
author_name: eccenca GmbH
github_page: https://gitlab.eccenca.com/elds/plugins/cmem-plugin-irdi
project_description: Create unique International Registration Data Identifier (IRDI).
project_slug: irdi
project_type: plugin
pypi: true

